type Todo {
  id: ID!
  userid: String!
  title: String!
  completed: Boolean!
  createdAt: Datetime!
  updatedAt: Datetime!
  user: User!
}

type Query {
  todos: [Todo!]!
}

type Mutation {
  addTodo(title: String!): Todo!
  updateTodo(todoId: String!, title: String, completed: Boolean): Todo!
  deleteTodo(todoId: String!): Todo!
}

fragment TodoFragment on Todo {
  id
  title
  completed
  createdAt
  updatedAt
  user {
    ...userFragment
  }
}

query Todos {
  todos {
    ...TodoFragment
  }
}

mutation AddTodo($title: String!) {
  addTodo(title: $title) {
    ...TodoFragment
  }
}

mutation UpdateTodo($todoId: String!, $title: String, $completed: Boolean) {
  updateTodo(todoId: $todoId, title: $title, completed: $completed) {
    ...TodoFragment
  }
}

mutation DeleteTodo($todoId: String!) {
  deleteTodo(todoId: $todoId) {
    ...TodoFragment
  }
}
